#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_presets.h"
#include "special_presets.h"
#include "textures.h"

#include "make_const_nonconst.h"
#include "levels/bowser_2/texture.inc.c"
#include "levels/bowser_2/tilting_platform/model.inc.c"
#include "levels/bowser_2/areas/1/1/model.inc.c"
#include "levels/bowser_2/areas/1/collision.inc.c"
#include "levels/bowser_2/tilting_platform/collision.inc.c"
