extern const GeoLayout exclamation_box_000_switch_opt1[];
extern const GeoLayout exclamation_box_000_switch_opt2[];
extern const GeoLayout exclamation_box_000_switch_opt3[];
extern const GeoLayout exclamation_box_geo[];
extern Vtx exclamation_box_000_displaylist_mesh_vtx_0[46];
extern Gfx exclamation_box_000_displaylist_mesh_tri_0[];
extern Vtx exclamation_box_000_displaylist_mesh_vtx_1[36];
extern Gfx exclamation_box_000_displaylist_mesh_tri_1[];
extern Vtx exclamation_box_000_Offset_001_mesh_vtx_0[61];
extern Gfx exclamation_box_000_Offset_001_mesh_tri_0[];

extern Gfx exclamation_box_000_displaylist_mesh[];
extern Gfx exclamation_box_000_displaylist_mesh_mat_override_top_bottom_metal_0[];
extern Gfx exclamation_box_000_displaylist_mesh_mat_override_top_bottom_vanish_1[];
extern Gfx exclamation_box_000_displaylist_mesh_mat_override_top_bottom_normal_2[];
extern Gfx exclamation_box_000_Offset_001_mesh[];
extern Gfx exclamation_box_000_Offset_001_mesh_mat_override_top_bottom_metal_0[];
extern Gfx exclamation_box_000_Offset_001_mesh_mat_override_top_bottom_vanish_1[];
extern Gfx exclamation_box_000_Offset_001_mesh_mat_override_top_bottom_normal_2[];
extern Gfx exclamation_box_material_revert_render_settings[];

