COURSE_ACTS(COURSE_BOB, _(" 1 ZONA DE BOB-BOMBATE"),
       _("REI BOB-BOMBA NA MONTANHA")     , _("CORRIDA CONTRA O KOPA VELOSO")  , _("ATIRE NA ILHA FLUTUANTE"),
       _("ACHE AS 8 MOEDAS VERMELHAS")    , _("MARIO ALADO, VOE PELO CÉU")     , _("NA CASINHA DO CHOMP CHOMP"))

COURSE_ACTS(COURSE_WF,  _(" 2 FORTALEZA ESMAGÃO"),
       _("ESMAGUE O REI ESMAGÃO")          , _("PARA O TOPO DA FORTALEZA!")     , _("DISPARO NO AZUL DO CÉU"),
       _("MOEDAS VERMELHAS DAS ILHAS")    , _("CAIA NA ILHA ENJAULADA")        , _("DESTRUA O MURO COM O CANHÃO!"))

COURSE_ACTS(COURSE_JRB, _(" 3 BAÍA DE TODOS OS PIRATAS"),
       _("OS BENS DO NAVIO NAUFRAGADO")   , _("VEM AQUI PARA FORA, MOREIA!")   , _("TESOURO NA CAVERNA SUBMARINA"),
       _("8 MOEDAS DO NAVIO À DERIVA")    , _("DISPARE NO PILAR DE PEDRA")     , _("CONTRA A CORRENTE DE JATO"))

COURSE_ACTS(COURSE_CCM, _(" 4 FRIA MONTANHA FRIA"),
       _("UM ESCORREGA CONGELANTE")        , _("PEQUENA PINGUIM PERDIDA")      , _("CORRIDA DO GRANDE PINGUIM"),
       _("DESLIZANDO POR MOEDAS VERMELHAS"), _("O BONECO SEM CABEÇA")          , _("SUPERSALTO ESCALADA ESCONDIDO"))

COURSE_ACTS(COURSE_BBH, _(" 5 MEDONHA MANSÃO BU"),
       _("CACE FANTASMAS E O GRANDE BU")  , _("NO CARROSSEL DO GRANDE BU")     , _("ENIGMA DOS LIVROS ASSOMBRADOS"),
       _("MOEDA VERMELHA, CADÊ VOCÊ?")    , _("A VARANDA DO GRANDE BU")        , _("OLHO POR OLHO NA SALA SECRETA"))

COURSE_ACTS(COURSE_HMC, _(" 6 CAVERNA NEBULOSA"),
       _("O MONSTRO DO LAGO SUBTERRÂNEO") , _("ELEVANDO-SE POR 8 MOEDAS")      , _("MARIO METÁLICO DEVE CORRER"),
       _("NAVEGANDO NO LABIRINTO TÓXICO") , _("SAÍDA DE EMERGÊNCIA DO LABIRINTO"), _("O QUE AS ROCHAS ESCONDEM"))

COURSE_ACTS(COURSE_LLL, _(" 7 LAGO DE LAVA LETAL"),
       _("DERRUBANDO O GRANDE BRIGÃO")    , _("BRIGUE COM OS BRIGÕES")         , _("QUEBRA-CABEÇA DE 8 MOEDAS"),
       _("CRUZANDO O TRONCO ROLANTE")     , _("PASSOS QUENTES NO VULCÃO")      , _("ANDE NO ELEVADOR VULCÂNICO"))

COURSE_ACTS(COURSE_SSL, _(" 8 DESERTO MOVEDIÇO"),
       _("NAS GARRAS DO KLEPTO ABUTRE")   , _("BRILHANDO NO TOPO DA PIRÂMIDE") , _("GIGANTE INTERIOR DA PIRÂMIDE"),
       _("ÀQUELE QUE PISA NOS 4 PILARES..."), _("VOO LIVRE POR MOEDAS VERMELHAS"), _("ENIGMA DENTRO DA PIRÂMIDE"))

COURSE_ACTS(COURSE_DDD, _(" 9 ÁGUAS ANGUSTIANTES"),
       _("NO SUBMARINO DO BOWSER")        , _("UM TURBILHÃO DE BAÚS")          , _("MOEDAS VERMELHAS ENTRE MASTROS"),
       _("ANÉIS CONTRA A CORRENTE DE JATO"), _("O PRESENTE DA ARRAIA")          , _("QUANDO SE USAM DOIS BONÉS..."))

COURSE_ACTS(COURSE_SL,  _("10 TERRA DAS NEVES"),
       _("NO CABEÇÃO DO BONECÃO DE NEVE") , _("FICA FRIO COM O FRIGÃO")        , _("NO FUNDO DA OBRA GEL-ARTE"),
       _("RODOPIOS NO LAGO CONGELANTE")   , _("ANDANDO DE CASCO POR 8 MOEDAS") , _("NO IGLU DOS HELIFLORES"))

COURSE_ACTS(COURSE_WDW, _("11 CIDADE MOLHA-SECA"),
       _("SETINHAS AZUIS CHOCANTES")      , _("O PICO DA CIDADE")              , _("5 SEGREDOS NO RASO E NO CÉU"),
       _("ELEVADOR EXPRESSO! ANDE LOGO!") , _("8 MOEDAS NO CENTRO DA CIDADE")  , _("CORRA CONTRA O TEMPO NO CENTRO"))

COURSE_ACTS(COURSE_TTM, _("12 ALTA MONTANHA ALTA"),
       _("ESCALE A ALTA MONTANHA")        , _("A GAIOLA DO MACACO TRAVESSO")   , _("FUNGOS ALTOS, MOEDAS VERMELHAS"),
       _("O MISTÉRIO DO ESCORREGA")       , _("VISTA DESLUMBRANTE DA PONTE")   , _("ATIRE NO COGUMELO ISOLADO!"))

COURSE_ACTS(COURSE_THI, _("13 ILHA PEQUENORME"),
       _("ARRANQUE AS GRANDES PIRANHAS")  , _("NO TOPO DA ILHA ENORME")        , _("REVANCHE CONTRA O KOPA VELOSO"),
       _("5 SEGREDINHOS DA ILHA PEQUENINA"), _("MOEDAS VERMELHAS DA FLORAGARTA"), _("A FÚRIA DA FLORAGARTA"))

COURSE_ACTS(COURSE_TTC, _("14 RELÓGIO TIQUE TIQUE"),
       _("ATRÁS DAS GRADES")              , _("O POÇO E OS PÊNDULOS")          , _("DÁ UM TEMPO AO PONTEIRO"),
       _("TUMBO LÁ NO TOPO")              , _("SALTE NOS BARRÕES SINCRONIZADOS"), _("RELÓGIO ÀS 12, MOEDAS 8"))

COURSE_ACTS(COURSE_RR,  _("15 PERCURSO ARCO-ÍRIS"),
       _("NO BARCO NO ARCO-ÍRIS")         , _("A MANSÃO NO CÉU")               , _("8 MOEDAS DO LABIRINTO VERTICAL"),
       _("BALANÇANDO NA BRISA")           , _("TRIÂNGULOS TROCA-TROCA")        , _("A ILHA ALÉM DO ARCO-ÍRIS"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER NO MUNDO DAS TREVAS"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER NO MAR DE LAVA"))
SECRET_STAR(COURSE_BITS,  _("   BOWSER NO CÉU!"))
SECRET_STAR(COURSE_PSS,   _("   ESCORREGA ESCONDIDO DA PRINCESA"))
SECRET_STAR(COURSE_COTMC, _("   CACHOEIRA DO BOTÃO DO METAL"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE DO BOTÃO DAS ASAS"))
SECRET_STAR(COURSE_VCUTM, _("   FOSSO DO BOTÃO DA TRANSPARÊNCIA"))
SECRET_STAR(COURSE_WMOTR, _("   BATENDO ASAS SOBRE O ARCO-ÍRIS"))
SECRET_STAR(COURSE_SA,    _("   O AQUÁRIO SECRETO"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   ESTRELAS DO CASTELO"))

EXTRA_TEXT(0, _("UMA ESTRELA SECRETA DO CASTELO!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
