COURSE_ACTS(COURSE_BOB, _(" 1 BOB-OMB BATTLEFIELD"),
       _("BIG BOB-OMB ON THE SUMMIT")     , _("FOOTRACE WITH GEMERL THE GIZOID") , _("SHOOT TO THE ISLAND IN THE SKY"),
       _("FIND THE 8 SILVER RINGS")          , _("CREAM WINGS TO THE SKY")        , _("BEHIND CHAIN CHOMP'S GATE"))

COURSE_ACTS(COURSE_WF, _(" 2 WHOMP'S FORTRESS"),
       _("CHIP OFF WHOMP'S BLOCK")        , _("TO THE TOP OF THE FORTRESS")    , _("SHOOT INTO THE WILD BLUE"),
       _("RED COINS ON THE FLOATING ISLE"), _("FALL ONTO THE CAGED ISLAND")    , _("BLAST AWAY THE WALL"))

COURSE_ACTS(COURSE_JRB, _(" 3 JOLLY ROGER BAY"),
       _("PLUNDER IN THE SUNKEN SHIP")    , _("CAN THE EEL COME OUT TO PLAY?") , _("TREASURE OF THE OCEAN CAVE"),
       _("SILVER RINGS ON THE SHIP AFLOAT")  , _("BLAST TO THE STONE PILLAR")     , _("THROUGH THE JET STREAM"))

COURSE_ACTS(COURSE_CCM, _(" 4 COOL, COOL MOUNTAIN"),
       _("SLIP SLIDIN' AWAY")             , _("LI'L CHAO LOST")             , _("BIG PENGUIN RACE"),
       _("FROSTY SLIDE FOR 8 SILVER RINGS")  , _("SNOWMAN'S LOST HIS HEAD")       , _("WALL KICKS WILL WORK"))

COURSE_ACTS(COURSE_BBH, _(" 5 BIG BOO'S HAUNT"),
       _("GO ON A GHOST HUNT")            , _("RIDE BIG BOO'S MERRY-GO-ROUND") , _("SECRET OF THE HAUNTED BOOKS"),
       _("SEEK THE 8 SILVER RINGS")          , _("KING BIG BOO'S BALCONY")             , _("EYE TO EYE IN THE SECRET ROOM"))

COURSE_ACTS(COURSE_HMC, _(" 6 HAZY MAZE CAVE"),
       _("SWIMMING BEAST IN THE CAVERN")  , _("ELEVATE FOR 8 SILVER RINGS")       , _("CHROME-HEAD CREAM CAN MOVE!"),
       _("NAVIGATING THE TOXIC MAZE")     , _("A-MAZE-ING EMERGENCY EXIT")     , _("WATCH FOR ROLLING ROCKS"))

COURSE_ACTS(COURSE_LLL, _(" 7 LETHAL LAVA LAND"),
       _("BOIL THE BIG CRAWL")            , _("BULLY THE CRAWLS")             , _("8-RING PUZZLE WITH 15 PIECES"),
       _("RED-HOT LOG ROLLING")           , _("HOT-FOOT-IT INTO THE VOLCANO")  , _("ELEVATOR TOUR IN THE VOLCANO"))

COURSE_ACTS(COURSE_SSL, _(" 8 SHIFTING SAND LAND"),
       _("IN THE TALONS OF THE BIG BIRD") , _("SHINING ATOP THE PYRAMID")      , _("INSIDE THE ANCIENT PYRAMID"),
       _("STAND TALL ON THE FOUR PILLARS"), _("FREE FLYING FOR 8 SILVER RINGS")   , _("PYRAMID PUZZLE"))

COURSE_ACTS(COURSE_DDD, _(" 9 DIRE, DIRE DOCKS"),
       _("BOARD EGGMAN'S SUB")            , _("CHESTS IN THE CURRENT")         , _("POLE-JUMPING FOR SILVER RINGS"),
       _("THROUGH THE JET STREAM")        , _("THE MANTA RAY'S REWARD")        , _("COLLECT THE CAPS..."))

COURSE_ACTS(COURSE_SL, _("10 SNOWMAN'S LAND"),
       _("SNOWMAN'S BIG HEAD")            , _("CHILL WITH THE BULLY")          , _("IN THE DEEP FREEZE"),
       _("WHIRL FROM THE FREEZING POND")  , _("SHELL SHREDDIN' FOR SILVER RINGS") , _("INTO THE IGLOO"))

COURSE_ACTS(COURSE_WDW, _("11 WET-DRY WORLD"),
       _("SHOCKING ARROW LIFTS!")         , _("TOP O' THE TOWN")               , _("SECRETS IN THE SHALLOWS & SKY"),
       _("EXPRESS ELEVATOR--HURRY UP!")   , _("GO TO TOWN FOR SILVER RINGS")      , _("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12 TALL, TALL MOUNTAIN"),
       _("SCALE THE MOUNTAIN")            , _("MYSTERY OF THE COCONUTS CAGE")    , _("SCARY 'SHROOMS, SILVER RINGS"),
       _("MYSTERIOUS MOUNTAINSIDE")       , _("BREATHTAKING VIEW FROM BRIDGE") , _("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 TINY-HUGE ISLAND"),
       _("PLUCK THE BEANSTALK FLOWER")      , _("THE TIP TOP OF THE HUGE ISLAND"), _("REMATCH WITH GEMERL THE GIZOID"),
       _("FIVE ITTY BITTY SECRETS")       , _("WIGGLER'S SILVER RINGS")           , _("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 TICK TOCK CLOCK"),
       _("ROLL INTO THE CAGE")            , _("THE PIT AND THE PENDULUMS")     , _("GET A HAND"),
       _("STOMP ON THE THWOMP")           , _("TIMED JUMPS ON MOVING BARS")    , _("STOP TIME FOR SILVER RINGS"))

COURSE_ACTS(COURSE_RR, _("15 RAINBOW RIDE"),
       _("CRUISER CROSSING THE RAINBOW")  , _("THE BIG HOUSE IN THE SKY")      , _("RINGS AMASSED IN A MAZE"),
       _("SWINGIN' IN THE BREEZE")        , _("TRICKY TRIANGLES!")             , _("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(COURSE_BITDW, _("   EGGMAN IN THE DARK WORLD"))
SECRET_STAR(COURSE_BITFS, _("   EGGMAN IN THE FIRE SEA"))
SECRET_STAR(COURSE_BITS, _("   EGGMAN IN THE SKY"))
SECRET_STAR(COURSE_PSS, _("   THE BUNNY'S SECRET SLIDE"))
SECRET_STAR(COURSE_COTMC, _("   CAVERN OF THE METAL LOCKET"))
SECRET_STAR(COURSE_TOTWC, _("   TOWER OF THE WING LOCKET"))
SECRET_STAR(COURSE_VCUTM, _("   VANISH LOCKET UNDER THE MOAT"))
SECRET_STAR(COURSE_WMOTR, _("   WING CREAM OVER THE RAINBOW"))
SECRET_STAR(COURSE_SA, _("   THE SECRET AQUARIUM"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   CASTLE SECRET STAR RINGS"))

EXTRA_TEXT(0, _("ONE OF THE CASTLE'S SECRET STAR RINGS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
