
/* Music Defines */

.set SEQ_VARIATION,                     0x80

.set SEQ_SOUND_PLAYER,                  0x0000
.set SEQ_EVENT_CUTSCENE_COLLECT_STAR,   0x0001
.set SEQ_MENU_TITLE_SCREEN,             0x0002
.set SEQ_LEVEL_GRASS,                   0x0003
.set SEQ_LEVEL_INSIDE_CASTLE,           0x0004
.set SEQ_LEVEL_WATER,                   0x0005
.set SEQ_LEVEL_HOT,                     0x0006
.set SEQ_LEVEL_BOSS_KOOPA,              0x0007
.set SEQ_LEVEL_SNOW,                    0x0008
.set SEQ_LEVEL_SLIDE,                   0x0009
.set SEQ_LEVEL_SPOOKY,                  0x000A
.set SEQ_EVENT_PIRANHA_PLANT,           0x000B
.set SEQ_LEVEL_UNDERGROUND,             0x000C
.set SEQ_MENU_STAR_SELECT,              0x000D
.set SEQ_EVENT_POWERUP,                 0x000E
.set SEQ_EVENT_METAL_CAP,               0x000F
.set SEQ_EVENT_KOOPA_MESSAGE,           0x0010
.set SEQ_LEVEL_KOOPA_ROAD,              0x0011
.set SEQ_EVENT_HIGH_SCORE,              0x0012
.set SEQ_EVENT_MERRY_GO_ROUND,          0x0013
.set SEQ_EVENT_RACE,                    0x0014
.set SEQ_EVENT_CUTSCENE_STAR_SPAWN,     0x0015
.set SEQ_EVENT_BOSS,                    0x0016
.set SEQ_EVENT_CUTSCENE_COLLECT_KEY,    0x0017
.set SEQ_EVENT_ENDLESS_STAIRS,          0x0018
.set SEQ_LEVEL_BOSS_KOOPA_FINAL,        0x0019
.set SEQ_EVENT_CUTSCENE_CREDITS,        0x001A
.set SEQ_EVENT_SOLVE_PUZZLE,            0x001B
.set SEQ_EVENT_TOAD_MESSAGE,            0x001C
.set SEQ_EVENT_PEACH_MESSAGE,           0x001D
.set SEQ_EVENT_CUTSCENE_INTRO,          0x001E
.set SEQ_EVENT_CUTSCENE_VICTORY,        0x001F
.set SEQ_EVENT_CUTSCENE_ENDING,         0x0020
.set SEQ_MENU_FILE_SELECT,              0x0021
.ifndef VERSION_JP
.set SEQ_EVENT_CUTSCENE_LAKITU,         0x0022
.endif
